### ISSUE TITLE
AddNurseForm - Implement add new nurse form

### ISSUE THREAD

**Issue by jburton6** [mstudar1/clinic#14]
- [x] Createform similar to register patient form, but for adding a new nurse to the system as admin
- [x] Create NurseDAL
- [x] Create NurseController
- [x] Wire form to actions
- [x] Set start position to center
- [x] Change DropDownStyle of Gender combobox from DropDown to DropDownList

I got the form basically up and running. It will add an entry properly to the DB based on form information. Here is what still needs to be done:

- [x] Implement cancel button
- [x] Upon successful add nurse action, bring up popup success message with OK button. When button is clicked the add nurse form is closed.
- [x] Implement date picker for DOB
- [x] Implement gender combobox
- [ ] Make all reasonable entries of SSN/Phone/Zip Codes get formatted uniformly before being added to DB
- [x] Clean up error messages
- [x] Tab control should be disabled while registration is taking place

**Comment by jburton6** [comment]
I got the form basically up and running.  It will add an entry properly to the DB based on form information.  Here is what still needs to be done:
- [x] Implement cancel button
- [x] Upon successful add nurse action, bring up popup success message with OK button.  When button is clicked the add nurse form is closed.
- [x] Implement date picker for DOB
- [x] Implement gender combobox
- [ ] Make all reasonable entries of SSN/Phone/Zip Codes get formatted uniformly before being added to DB
- [x] Clean up error messages
- [x] Tab control should be disabled while registration is taking place

**Comment by mstudar1** [comment]
- [x] Set start position to center

**Comment by mstudar1** [comment]
- [x] Change DropDownStyle of Gender combobox from DropDown to DropDownList

**Comment by jburton6** [comment]
Closing this one.  The last feature would be nice but we have it essentially handled for now.
