### ISSUE TITLE
Appearance Tweeks

### ISSUE THREAD

**Issue by jburton6** [mstudar1/clinic#7]
These are just a few little appearance things that I think are worth touching up:
- [ ] Add labels to all search fields
- [ ] Reposition city to be next to state on Register Patient pop up form
- [x] Change label at top of window to show user's name AND username.  (this is a project requirement)
- [ ] Might be worth adding brief instructions at the top of each page

**Comment by mstudar1** [comment]
- [ ] Remove period from error message label on login form

**Comment by jburton6** [comment]
Modified the label at top of TabPage to show full name and userId.
