### ISSUE TITLE
Implement Search Features

### ISSUE THREAD

**Issue by jburton6** [mstudar1/clinic#8]
The search features on all tab pages need to be implemented:
- [x] Search features need to be wired to the controllers
- [x] Clear button needs action
- [x] List view needs to populate from DB

**Comment by jburton6** [comment]
AB - I'm working on the search feature for appointments.  The other might conflict with work you guys are doing.  This will also allow me to move into the edit appointments feature.

**Comment by mstudar1** [comment]
I didn't do anything with appointments per the above note, but the other search functions that were already in the view have been added.
